### PR TITLE
Fix _LazyBatchNorm import broken by torch 1.10.0

### LINKED ISSUE #22: Error import _LazyBatchNorm
`from torch.nn.modules.batchnorm import _BatchNorm, _LazyBatchNorm
ImportError: cannot import name '_LazyBatchNorm' from 'torch.nn.modules.batchnorm' (/Users/xx/.pyenv/versions/3.9.6/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py)`

### PR DESCRIPTION
**Pull request by calvinmccarter-at-lightmatter**
Fixes #22 .

This PR is necessitated by this PyTorch PR which is now part of 1.10.0 https://github.com/pytorch/pytorch/pull/60982

~~Unfortunately, this PR will break onnx2pytorch for torch<1.10.0, so it is not ready to be merged until I fix this.~~
Edit: this PR now works with torch < 1.10.0 and torch >= 1.10.0.

### CODE REVIEW

**Comment by ZiyuBao** [comment]
I installed torch 1.10.0 but the problem was not resolved. Editing onnx2pytorch/operations/batchnorm.py and change _LazyBatchNorm to _LazyNormBase fixes the problem!b [the issue](https://github.com/ToriML/onnx2pytorch/issues/22#issuecomment-955132898)

**Comment by calvinmccarter-at-lightmatter** [comment]
@Talmaj - this PR is now ready for review.

**Comment by calvinmccarter-at-lightmatter** [comment]
@Talmaj - this PR is now ready for review.

Also resolves #25 (same as #23 ).

**Comment by Talmaj** [comment]
@calvinmccarter-at-lightmatter can you add to tox.ini a new test env for `torch<=1.9.0` ?
```
[tox]
envlist = clean,py36,py37,py38,py38-torch19,py39

[testenv]
passenv =
    CIRCLE*
    KMP_DUPLICATE_LIB_OK
deps =
    -rrequirements.txt
    torch19: torch <= 1.9.0.
    pytest-cov
commands =
    pytest --cov --cov-append --cov-report term --cov-report html tests/
```

**Comment by calvinmccarter-at-lightmatter** [comment]
@Talmaj - done! and PR #27 is ready for review as well
